language: dart
sudo: false
dart:
  - dev
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer: --fatal-warnings --fatal-lints lib
branches:
  only: [master]
cache:
  directories:
    - $HOME/.pub-cache