name: uuid_type
description: 'UUID type, parser and generators. Supported RFC versions are: v1, v4, v5'
version: 0.8.0-beta
author: Denis Portnov <denixport@gmail.com>
uploader: Denis Portnov <denixport@gmail.com>
homepage: https://github.com/denixport/dart-uuid
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  crypto: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: '^1.3.0'
  benchmark_harness: '^1.0.0'
