name: uuid_type
description: 'UUID type, parser and generators. Can generate v1, v4, and v5 UUIDs'
version: 1.0.2
author: Denis Portnov <denixport@gmail.com>
uploader: Denis Portnov <denixport@gmail.com>
homepage: https://github.com/denixport/dart-uuid
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  crypto: '>=2.0.0 <3.0.0'
dev_dependencies:
  pedantic: '>=1.0.0'
  test: '^1.3.0'
  
